### ISSUE TITLE
Error upon connection

### ISSUE THREAD

**Issue by awsumturtlee** [latenightprogrammers/RotMGRPC#1]
I get up to "Connected to rich presence!" after that it gives an error for a split second and the cmd just closes.

Any help?

**Comment by neopkr** [comment]
Sorry for the late response, we were having problems with the names and errors of the RealmEye page itself, so we couldn't fix the problem quickly as they were constantly fixing the RealmEye page, currently it seems to work fine.

If the problem persists in your RealmEye profile you have to put everything public except your last location.

And if the problem still persists, contact us by opening another ticket.
