### ISSUE TITLE
pypresence.exceptions.DiscordNotFound

### ISSUE THREAD

**Issue by Cimininxi** [latenightprogrammers/RotMGRPC#2]
Hello, i download the program and i got the follow error:
![Error](https://github.com/latenightprogrammers/RotMGRPC/assets/142637470/c5857056-80b6-453d-b826-020d65a2bf8e)

After encountering that error, the program crashed immediately. I had to open the .exe file from the CMD to be able to view the error.

PD: I have discord in my pc.

**Comment by neopkr** [comment]
It appears that you haven't opened Discord or you might not have Discord installed directly. Is a normal error coming from 'pypresence'. I'm going to add a loop to wait for the user to open Discord in this case. This way, we can prevent the application from crashing and have it enter a waiting mode.
